### PR TITLE
Fix handling of empty metadata when uploading data files

### PR DESCRIPTION
**Pull request by shoeffner**
Relates to datalad/datalad-dataverse#320: Handles "empty" metadata and is an alternative to datalad/datalad-dataverse#322.

### CODE REVIEW

**Comment by pdurbin** [comment]
At a high level, this seems like a good fix. The JSON should be optional.

**Review by JR-1991 — APPROVED** [review]
LGTM - Thanks!

**Comment by adswa** [comment]
many thanks again for this fix :) Is there by chance a pyDataverse release upcoming? Otherwise, I'll let datalad-dataverse depend on a development version from github for the time being. :)

**Comment by pdurbin** [comment]
@adswa hi! I'll defer to @JR-1991 on the timing of the release but it should be [0.3.4](https://github.com/gdcc/pyDataverse/milestones/0.3.4). I just assigned that milestone to this PR (which was a PR to #203 which also has that milestone).

I don't see any problem with using a dev version, in the meantime.

**Comment by JR-1991** [comment]
@adswa - Once the final two pull requests are merged and all issues are resolved within the [milestone](https://github.com/gdcc/pyDataverse/milestones/0.3.4), we will be all set to release the next version 0.3.4 of pyDataverse. Both are relatively small and I am confident that we will have the release out very soon.

**Pull request merged**
