### PR TITLE
Async requests

### PR DESCRIPTION
**Pull request by JR-1991**
**Changes this PR introduces**

This pull request adds async support to pyDataverse based on the previously merged switch from `requests` to `httpx`. Asynchronous requests significantly improve pyDataverse's performance by using concurrent requests. The implementation provides a seamless usage to work either sync or async by the usage of a context manager.

_Small benchmark_

* 100 calls to `api/info/version` to [demo.dataverse.org](demo.dataverse.org)
* Synchronous --> ~35s
* Asynchronous --> ~0.5s 🏎️

**Overview**

* Added `_sync_request` and `_async_request` base methods
* Added Context manager to `API` to enable async requests
* Small test to verify async requests are working

**Example**

_Synchronous_

```python
native_api = NativeApi("https://demo.dataverse.org")
response = native_api.get_info_version()
```

_Asynchronous_

```python
import asyncio
from pyDataverse.api import NativeApi


async def run_async(native_api):
    async with native_api:
        tasks = [native_api.get_info_version() for _ in range(100)]
        responses = await asyncio.gather(*tasks)

if __name__ == "__main__":
    native_api = NativeApi("https://demo.dataverse.org")
    asyncio.run(run_async(native_api))
```

### CODE REVIEW

**Comment by haeussma** [comment]
Tested the example with `python=3.11`. 

Notices missing dependency `urllib3` which is not specified in the requirements but imported in `src/pyDataverse/__init__.py`.

Except for that the example works as expected.

**Review by haeussma — COMMENTED** [review]
Tested the example with `python=3.11`. 

Notices missing dependency `urllib3` which is not specified in the requirements but imported in `src/pyDataverse/__init__.py`.

Except for that the example works as expected.

**Review by haeussma — APPROVED** [review]
Tested the example with `python=3.11`. 

Notices missing dependency `urllib3` which is not specified in the requirements but imported in `src/pyDataverse/__init__.py`.

Except for that the example works as expected.

**Comment by JR-1991** [comment]
@haeussma thanks for the review! I have added `urllib3` to the list of dependencies.

**Pull request merged**
