### PR TITLE
More file upload descriptors

### PR DESCRIPTION
**Pull request by Ajax23**
Add an optional file description and directory field to the file upload function. The directory field can be used to sort data for the new tree-view listing in dataverse.

### CODE REVIEW

**Comment by skasberger** [comment]
I recommend using the develop branch, where this issue is already solved, or wait for the new release coming this/next week. 

Fixed function: https://github.com/gdcc/pyDataverse/blob/a9f730d680d83a66b9876df4f8e3913fe02aa5a7/src/pyDataverse/api.py#L1665

**Comment by skasberger** [comment]
But thank you very much for your contribution!

**Comment by Ajax23** [comment]
Ah, I am sorry for that... I forgot about the development branch since I am used to working alone on projects ^^

**Comment by skasberger** [comment]
I know exactly what you mean. It's my first project, where others are using it. :)

**Pull request closed without merging**
